# Formulations d'exemple SYNTHÉTIQUES (rédigées pour le projet, aucun vrai visiteur) : constats négatifs.
# Distinctions voulues : N1 = trajet/accès jusqu'à la ferme (pas la durée de la visite) ; N3 = la visite dure trop ;
# N4 = la visite est trop courte, on aurait voulu plus ; N8 = soif, soleil, pas de pause pendant la visite ;
# N9 = attente et retard ; N2 = prix flous ou annoncés tard (pas « trop cher » en soi) ; N6 = repas absent/insuffisant.

NEGATIVE_EXAMPLES = {
    "N1": {  # Chemin ou accès trop long ou difficile
        "en": [
            "The path to the farm was far too long.",
            "The road up there is really rough, our car barely made it.",
            "It was very hard to find the farm, no signs at all.",
            "The walk up from the main road was steep and exhausting.",
            "Getting there took ages on a muddy dirt track, not easy with older people.",
            "access is difficult",
            "The trail to the farm is slippery and dangerous after rain.",
            "Too far from town, the drive was long.",
            "We got lost twice on the way to the farm.",
        ],
        "fr": [
            "Le chemin pour arriver à la ferme était beaucoup trop long.",
            "La route pour monter est en très mauvais état, la voiture a eu du mal.",
            "La ferme est très difficile à trouver, aucun panneau.",
            "La montée depuis la route principale est raide et épuisante.",
            "Il faut des heures sur une piste boueuse pour y arriver, pas facile avec des personnes âgées.",
            "accès compliqué",
            "Le sentier jusqu'à la ferme est glissant et dangereux après la pluie.",
            "Trop loin de la ville, le trajet était long.",
            "On s'est perdus deux fois en route vers la ferme.",
        ],
        "de": [
            "Der Weg zur Farm war viel zu lang.",
            "Die Straße dort hinauf ist sehr schlecht, unser Auto kam kaum hoch.",
            "Die Farm war sehr schwer zu finden, gar keine Schilder.",
            "Der Aufstieg von der Hauptstraße war steil und anstrengend.",
            "Die Anfahrt über eine schlammige Piste dauerte ewig, mit älteren Leuten nicht einfach.",
            "anfahrt schwierig",
            "Der Pfad zur Farm ist nach Regen rutschig und gefährlich.",
            "Zu weit weg von der Stadt, die Fahrt war lang.",
            "Wir haben uns auf dem Weg zur Farm zweimal verfahren.",
        ],
        "es": [
            "El camino hasta la finca era demasiado largo.",
            "La carretera para subir está fatal, el coche casi no llega.",
            "Fue muy difícil encontrar la finca, no hay ninguna señal.",
            "La subida desde la carretera principal es empinada y agotadora.",
            "Llegar llevó horas por una pista de barro, nada fácil con personas mayores.",
            "acceso difícil",
            "El sendero a la finca resbala y es peligroso después de llover.",
            "Demasiado lejos del pueblo, el trayecto fue largo.",
            "Nos perdimos dos veces de camino a la finca.",
        ],
    },
    "N2": {  # Prix pas clairs ou annoncés trop tard
        "en": [
            "The price wasn't clear before we came.",
            "Nobody told us the cost until the end.",
            "We only found out about the extra fee for lunch afterwards.",
            "It was confusing what was included in the price.",
            "The guide quoted one price and then at the end we were asked for more, which felt awkward.",
            "prices unclear",
            "Please tell visitors the price in advance.",
            "We didn't know how much to pay or who to pay.",
            "Hidden costs at the end, a written price list would help.",
        ],
        "fr": [
            "Le prix n'était pas clair avant de venir.",
            "Personne ne nous a dit combien ça coûtait avant la fin.",
            "On a découvert après coup le supplément pour le repas.",
            "On ne savait pas trop ce qui était compris dans le prix.",
            "Le guide avait annoncé un prix et à la fin on nous a demandé plus, c'était gênant.",
            "prix pas clairs",
            "Merci d'annoncer le tarif à l'avance.",
            "On ne savait pas combien payer ni à qui.",
            "Des frais cachés à la fin, une liste de prix écrite aiderait.",
        ],
        "de": [
            "Der Preis war vorher nicht klar.",
            "Niemand hat uns bis zum Schluss gesagt, was es kostet.",
            "Vom Aufpreis fürs Mittagessen haben wir erst hinterher erfahren.",
            "Es war unklar, was im Preis enthalten ist.",
            "Der Guide nannte einen Preis und am Ende sollten wir mehr zahlen, das war unangenehm.",
            "preise unklar",
            "Bitte sagt den Besuchern den Preis im Voraus.",
            "Wir wussten nicht, wie viel wir wem zahlen sollten.",
            "Versteckte Kosten am Ende, eine schriftliche Preisliste wäre gut.",
        ],
        "es": [
            "El precio no estaba claro antes de venir.",
            "Nadie nos dijo cuánto costaba hasta el final.",
            "Nos enteramos después del suplemento por la comida.",
            "No quedaba claro qué incluía el precio.",
            "El guía dijo un precio y al final nos pidieron más, fue incómodo.",
            "precios poco claros",
            "Por favor, digan el precio por adelantado.",
            "No sabíamos cuánto pagar ni a quién.",
            "Costes ocultos al final, una lista de precios por escrito ayudaría.",
        ],
    },
    "N3": {  # Visite trop longue
        "en": [
            "The visit was too long.",
            "The tour dragged on, three hours was too much.",
            "It went on and on, the kids got bored halfway.",
            "A bit long, it could easily be shortened by an hour.",
            "We spent far too much time at each stop and by the end we were exhausted and just wanted to leave.",
            "way too long",
            "The whole thing lasted longer than we expected, it became tiring.",
            "Some parts felt endless.",
            "Make the tour shorter, it's too long for most people.",
        ],
        "fr": [
            "La visite était trop longue.",
            "Ça traînait en longueur, trois heures c'était trop.",
            "Ça n'en finissait pas, les enfants s'ennuyaient à mi-parcours.",
            "Un peu long, on pourrait facilement raccourcir d'une heure.",
            "On est restés beaucoup trop longtemps à chaque étape, à la fin on était épuisés et on voulait partir.",
            "beaucoup trop long",
            "L'ensemble a duré plus longtemps que prévu, c'est devenu fatigant.",
            "Certains moments semblaient interminables.",
            "Raccourcissez la visite, elle est trop longue pour la plupart des gens.",
        ],
        "de": [
            "Die Führung war zu lang.",
            "Es hat sich gezogen, drei Stunden waren zu viel.",
            "Es hörte gar nicht auf, die Kinder haben sich nach der Hälfte gelangweilt.",
            "Etwas lang, man könnte locker eine Stunde kürzen.",
            "Wir waren an jeder Station viel zu lange und am Ende waren wir erschöpft und wollten nur noch gehen.",
            "viel zu lang",
            "Das Ganze dauerte länger als erwartet und wurde anstrengend.",
            "Manche Teile kamen mir endlos vor.",
            "Macht die Tour kürzer, sie ist für die meisten zu lang.",
        ],
        "es": [
            "La visita fue demasiado larga.",
            "Se hizo eterna, tres horas era demasiado.",
            "No se acababa nunca, los niños se aburrieron a mitad.",
            "Un poco larga, se podría acortar una hora fácilmente.",
            "Estuvimos demasiado tiempo en cada parada y al final estábamos agotados y solo queríamos irnos.",
            "demasiado larga",
            "Todo duró más de lo que esperábamos y se volvió cansado.",
            "Algunas partes parecían interminables.",
            "Acorten el recorrido, es demasiado largo para la mayoría.",
        ],
    },
    "N4": {  # Visite trop courte
        "en": [
            "The visit was too short.",
            "It was over too quickly, we wanted more time.",
            "We felt rushed, only one hour is not enough.",
            "I wish we could have stayed longer in the fields.",
            "It all went so fast that we didn't have time to ask questions or enjoy the place properly.",
            "too short!",
            "Too quick, I'd happily pay for a longer version.",
            "Over before it really started.",
            "Not enough time at the farm.",
        ],
        "fr": [
            "La visite était trop courte.",
            "C'est passé trop vite, on aurait voulu plus de temps.",
            "On s'est sentis pressés, une heure ce n'est pas assez.",
            "J'aurais aimé rester plus longtemps dans les champs.",
            "Tout est allé si vite qu'on n'a pas eu le temps de poser des questions ni de profiter de l'endroit.",
            "trop court !",
            "Trop rapide, je paierais volontiers pour une version plus longue.",
            "Fini avant d'avoir vraiment commencé.",
            "Pas assez de temps à la ferme.",
        ],
        "de": [
            "Die Führung war zu kurz.",
            "Es war viel zu schnell vorbei, wir hätten gern mehr Zeit gehabt.",
            "Wir fühlten uns gehetzt, eine Stunde reicht nicht.",
            "Ich wäre gern länger auf den Feldern geblieben.",
            "Alles ging so schnell, dass wir keine Zeit hatten, Fragen zu stellen oder den Ort zu genießen.",
            "zu kurz!",
            "Zu schnell, ich würde gern für eine längere Variante zahlen.",
            "Vorbei, bevor es richtig angefangen hat.",
            "Zu wenig Zeit auf der Farm.",
        ],
        "es": [
            "La visita fue demasiado corta.",
            "Se pasó muy rápido, queríamos más tiempo.",
            "Fuimos con prisas, una hora no es suficiente.",
            "Me habría gustado quedarme más tiempo en los campos.",
            "Todo fue tan rápido que no tuvimos tiempo de hacer preguntas ni de disfrutar del lugar.",
            "¡muy corta!",
            "Demasiado rápido, pagaría con gusto por una versión más larga.",
            "Se acabó antes de empezar de verdad.",
            "Poco tiempo en la finca.",
        ],
    },
    "N5": {  # Difficulté à se comprendre
        "en": [
            "It was hard to understand each other.",
            "We missed a lot because of the language barrier.",
            "The translation was difficult to follow.",
            "Sometimes we couldn't understand what Noor was saying.",
            "Without anyone speaking English well, a lot of the explanations got lost in translation.",
            "language barrier",
            "Communication was tricky, we often didn't understand the answers to our questions.",
            "Hard to communicate.",
            "Some written info in English would help us understand.",
        ],
        "fr": [
            "C'était difficile de se comprendre.",
            "On a raté beaucoup de choses à cause de la langue.",
            "La traduction était difficile à suivre.",
            "Parfois on ne comprenait pas ce que disait Noor.",
            "Sans personne qui parle bien français, beaucoup d'explications se perdaient dans la traduction.",
            "barrière de la langue",
            "La communication était compliquée, souvent on ne comprenait pas les réponses à nos questions.",
            "Difficile de communiquer.",
            "Un petit texte en français nous aiderait à comprendre.",
        ],
        "de": [
            "Es war schwer, sich zu verständigen.",
            "Wegen der Sprachbarriere haben wir viel verpasst.",
            "Der Übersetzung war schwer zu folgen.",
            "Manchmal haben wir nicht verstanden, was Noor gesagt hat.",
            "Da niemand gut Deutsch oder Englisch sprach, ging viel bei der Übersetzung verloren.",
            "sprachbarriere",
            "Die Verständigung war schwierig, die Antworten auf unsere Fragen haben wir oft nicht verstanden.",
            "Schwierige Kommunikation.",
            "Ein paar schriftliche Infos auf Englisch würden beim Verstehen helfen.",
        ],
        "es": [
            "Fue difícil entendernos.",
            "Nos perdimos mucho por el idioma.",
            "La traducción era difícil de seguir.",
            "A veces no entendíamos lo que decía Noor.",
            "Sin nadie que hablara bien español o inglés, muchas explicaciones se perdían en la traducción.",
            "barrera del idioma",
            "La comunicación fue complicada, muchas veces no entendíamos las respuestas a nuestras preguntas.",
            "Difícil comunicarse.",
            "Algo escrito en inglés nos ayudaría a entender.",
        ],
    },
    "N6": {  # Repas absent ou insuffisant
        "en": [
            "There was no meal, we were starving.",
            "Lunch was really small for the price.",
            "We expected food but nothing was offered.",
            "Not enough to eat after such a long morning.",
            "We were hungry after the walk and there was only a little snack, a proper meal would be nice.",
            "no lunch?",
            "The portions were tiny, we were still hungry.",
            "Some food would have been welcome.",
            "Please offer something to eat.",
        ],
        "fr": [
            "Il n'y avait pas de repas, on mourait de faim.",
            "Le déjeuner était vraiment maigre pour le prix.",
            "On s'attendait à manger mais rien n'était prévu.",
            "Pas assez à manger après une si longue matinée.",
            "On avait faim après la marche et il n'y avait qu'un petit en-cas, un vrai repas serait bien.",
            "pas de repas ?",
            "Les portions étaient minuscules, on avait encore faim.",
            "Un peu de nourriture aurait été bienvenu.",
            "Proposez quelque chose à manger s'il vous plaît.",
        ],
        "de": [
            "Es gab kein Essen, wir hatten riesigen Hunger.",
            "Das Mittagessen war für den Preis sehr dürftig.",
            "Wir hatten mit Essen gerechnet, aber es gab nichts.",
            "Nach so einem langen Vormittag zu wenig zu essen.",
            "Nach dem Rundgang hatten wir Hunger und es gab nur einen kleinen Snack, eine richtige Mahlzeit wäre schön.",
            "kein essen?",
            "Die Portionen waren winzig, wir waren immer noch hungrig.",
            "Etwas zu essen wäre willkommen gewesen.",
            "Bitte bietet etwas zu essen an.",
        ],
        "es": [
            "No hubo comida, nos moríamos de hambre.",
            "El almuerzo fue muy escaso para el precio.",
            "Esperábamos comer pero no había nada.",
            "Poca comida después de una mañana tan larga.",
            "Teníamos hambre después de la caminata y solo hubo un pequeño tentempié, una comida de verdad estaría bien.",
            "¿no hay comida?",
            "Las raciones eran diminutas, seguíamos con hambre.",
            "Algo de comer se habría agradecido.",
            "Por favor, ofrezcan algo de comer.",
        ],
    },
    "N7": {  # Toilettes ou hygiène
        "en": [
            "There were no toilets.",
            "The toilet was quite dirty.",
            "We couldn't wash our hands before eating.",
            "A clean bathroom would make a big difference.",
            "The latrine was hard to use and there was no soap or water to wash hands afterwards.",
            "toilets??",
            "Hygiene could be better, especially around the food.",
            "Please add a place to wash hands.",
            "Basic toilets would be appreciated.",
        ],
        "fr": [
            "Il n'y avait pas de toilettes.",
            "Les toilettes étaient assez sales.",
            "On n'a pas pu se laver les mains avant de manger.",
            "Des toilettes propres feraient une grande différence.",
            "Les latrines étaient difficiles à utiliser et il n'y avait ni savon ni eau pour se laver les mains.",
            "toilettes ??",
            "L'hygiène pourrait être meilleure, surtout autour de la nourriture.",
            "Ajoutez un endroit pour se laver les mains.",
            "Des toilettes, même simples, seraient appréciées.",
        ],
        "de": [
            "Es gab keine Toiletten.",
            "Die Toilette war ziemlich schmutzig.",
            "Wir konnten uns vor dem Essen nicht die Hände waschen.",
            "Ein sauberes WC würde viel ausmachen.",
            "Die Latrine war schwer zu benutzen und es gab weder Seife noch Wasser zum Händewaschen.",
            "toiletten??",
            "Die Hygiene könnte besser sein, vor allem beim Essen.",
            "Bitte eine Möglichkeit zum Händewaschen einrichten.",
            "Eine einfache Toilette wäre schön.",
        ],
        "es": [
            "No había baño.",
            "El baño estaba bastante sucio.",
            "No pudimos lavarnos las manos antes de comer.",
            "Un baño limpio marcaría la diferencia.",
            "La letrina era difícil de usar y no había jabón ni agua para lavarse las manos.",
            "¿¿baños??",
            "La higiene podría mejorar, sobre todo con la comida.",
            "Pongan un sitio para lavarse las manos.",
            "Unos baños básicos se agradecerían.",
        ],
    },
    "N8": {  # Manque d'eau, d'ombre ou de pause
        "en": [
            "We ran out of water, it was so hot.",
            "There was no shade in the field, the sun was brutal.",
            "We needed a break, there was nowhere to sit.",
            "Please offer drinking water to visitors.",
            "Standing in the full sun for an hour without water or a rest was really hard for us.",
            "need water and shade",
            "A short pause in the shade with something to drink would help.",
            "So thirsty during the tour.",
            "No rest stop at all, my mother was exhausted.",
        ],
        "fr": [
            "On n'avait plus d'eau, il faisait très chaud.",
            "Pas d'ombre dans le champ, le soleil tapait fort.",
            "On avait besoin d'une pause, il n'y avait nulle part où s'asseoir.",
            "Proposez de l'eau à boire aux visiteurs.",
            "Rester une heure en plein soleil sans eau ni pause, c'était vraiment dur pour nous.",
            "besoin d'eau et d'ombre",
            "Une petite pause à l'ombre avec à boire, ce serait bien.",
            "Tellement soif pendant la visite.",
            "Aucune pause, ma mère était épuisée.",
        ],
        "de": [
            "Uns ist das Wasser ausgegangen, es war so heiß.",
            "Auf dem Feld gab es keinen Schatten, die Sonne war brutal.",
            "Wir brauchten eine Pause, aber es gab nirgends einen Sitzplatz.",
            "Bitte bietet den Besuchern Trinkwasser an.",
            "Eine Stunde in der prallen Sonne ohne Wasser und ohne Pause war wirklich hart für uns.",
            "wasser und schatten fehlen",
            "Eine kurze Pause im Schatten mit etwas zu trinken wäre gut.",
            "So durstig während der Führung.",
            "Gar keine Pause, meine Mutter war erschöpft.",
        ],
        "es": [
            "Nos quedamos sin agua, hacía mucho calor.",
            "No había sombra en el campo, el sol pegaba fuerte.",
            "Necesitábamos un descanso y no había dónde sentarse.",
            "Ofrezcan agua para beber a los visitantes.",
            "Estar una hora a pleno sol sin agua ni descanso fue muy duro para nosotros.",
            "falta agua y sombra",
            "Una pausa corta a la sombra con algo de beber estaría bien.",
            "Muchísima sed durante la visita.",
            "Ninguna pausa, mi madre acabó agotada.",
        ],
    },
    "N9": {  # Attente, horaires non respectés
        "en": [
            "We had to wait a long time before it started.",
            "The tour started an hour late.",
            "Nobody was there when we arrived at the agreed time.",
            "We waited forty minutes for the guide.",
            "We were told nine o'clock but nothing happened until after ten and nobody explained why.",
            "long wait",
            "Please stick to the schedule.",
            "Lots of waiting around between activities.",
            "The timing was not respected at all.",
        ],
        "fr": [
            "On a dû attendre longtemps avant que ça commence.",
            "La visite a commencé avec une heure de retard.",
            "Personne n'était là à l'heure convenue.",
            "On a attendu le guide quarante minutes.",
            "On nous avait dit neuf heures mais rien n'a commencé avant dix heures passées, sans explication.",
            "longue attente",
            "Merci de respecter les horaires.",
            "Beaucoup d'attente entre les activités.",
            "Les horaires n'ont pas du tout été respectés.",
        ],
        "de": [
            "Wir mussten lange warten, bis es losging.",
            "Die Führung begann eine Stunde zu spät.",
            "Zur vereinbarten Zeit war niemand da.",
            "Wir haben vierzig Minuten auf den Guide gewartet.",
            "Uns wurde neun Uhr gesagt, aber vor zehn passierte nichts, und niemand hat erklärt, warum.",
            "lange wartezeit",
            "Bitte haltet euch an die Uhrzeiten.",
            "Viel Herumstehen und Warten zwischen den Programmpunkten.",
            "Die Zeiten wurden überhaupt nicht eingehalten.",
        ],
        "es": [
            "Tuvimos que esperar mucho antes de empezar.",
            "La visita empezó con una hora de retraso.",
            "No había nadie a la hora acordada.",
            "Esperamos al guía cuarenta minutos.",
            "Nos dijeron a las nueve pero nada empezó hasta pasadas las diez, sin ninguna explicación.",
            "mucha espera",
            "Por favor, respeten los horarios.",
            "Mucho tiempo esperando entre actividades.",
            "No se respetó el horario para nada.",
        ],
    },
    "N10": {  # Impossible d'acheter du café ou un souvenir
        "en": [
            "We couldn't buy any coffee at the end, which was a shame.",
            "There was nothing to buy, no coffee, no souvenirs.",
            "I wanted to bring coffee home but none was for sale.",
            "No shop or souvenir corner on the farm.",
            "We asked to buy a bag of beans but they said it all goes to the cooperative, so we left empty-handed.",
            "nothing for sale",
            "They didn't accept cards or mobile payment, so we couldn't buy the coffee.",
            "Shame there were no souvenirs.",
            "No coffee available to take away.",
        ],
        "fr": [
            "On n'a pas pu acheter de café à la fin, dommage.",
            "Il n'y avait rien à acheter, ni café ni souvenir.",
            "Je voulais rapporter du café mais il n'y en avait pas à vendre.",
            "Pas de boutique ni de coin souvenirs à la ferme.",
            "On a demandé à acheter un sachet de grains mais tout part à la coopérative, on est repartis les mains vides.",
            "rien à vendre",
            "Ni carte ni paiement mobile acceptés, donc impossible d'acheter le café.",
            "Dommage qu'il n'y ait pas de souvenirs.",
            "Aucun café à emporter.",
        ],
        "de": [
            "Wir konnten am Ende keinen Kaffee kaufen, schade.",
            "Es gab nichts zu kaufen, keinen Kaffee, keine Souvenirs.",
            "Ich wollte Kaffee mitnehmen, aber es wurde keiner verkauft.",
            "Kein Laden und keine Souvenirecke auf der Farm.",
            "Wir wollten eine Tüte Bohnen kaufen, aber alles geht an die Kooperative, also sind wir mit leeren Händen gegangen.",
            "nichts zu kaufen",
            "Keine Karten- oder Handyzahlung, deshalb konnten wir den Kaffee nicht kaufen.",
            "Schade, dass es keine Souvenirs gab.",
            "Kein Kaffee zum Mitnehmen erhältlich.",
        ],
        "es": [
            "No pudimos comprar café al final, una pena.",
            "No había nada para comprar, ni café ni recuerdos.",
            "Quería llevarme café pero no había para vender.",
            "No hay tienda ni rincón de recuerdos en la finca.",
            "Pedimos comprar una bolsa de granos pero todo va a la cooperativa, así que nos fuimos con las manos vacías.",
            "nada a la venta",
            "No aceptaban tarjeta ni pago por móvil, así que no pudimos comprar el café.",
            "Una pena que no hubiera recuerdos.",
            "No había café para llevar.",
        ],
    },
}
