# Formulations d'exemple SYNTHÉTIQUES (rédigées pour le projet, aucun vrai visiteur) : constats positifs.
# Chaque constat : 9 phrases par langue visiteur (en, fr, de, es), registres variés, courtes et longues.
# Ces phrases servent au rapprochement par similarité ; elles sont strictement séparées des données d'évaluation.

POSITIVE_EXAMPLES = {
    "P1": {  # Accueil chaleureux
        "en": [
            "Noor welcomed us so warmly.",
            "We felt really welcome from the moment we arrived.",
            "Such a kind and friendly host, she greeted us like family.",
            "The welcome was lovely, everyone was smiling.",
            "Thank you for the warm hospitality.",
            "Honestly the people were so nice to us, we felt at home right away.",
            "great welcome!!",
            "The family received us with so much kindness, it really touched us.",
            "Very friendly reception at the farm.",
        ],
        "fr": [
            "Noor nous a accueillis très chaleureusement.",
            "On s'est sentis bienvenus dès notre arrivée.",
            "Un accueil adorable, toute la famille souriait.",
            "Merci pour votre gentillesse et votre hospitalité.",
            "L'hôte était vraiment accueillante, on se sentait comme à la maison.",
            "super accueil",
            "La famille nous a reçus avec beaucoup de chaleur, ça nous a touchés.",
            "Des gens très gentils et très accueillants.",
            "On a été reçus comme des amis, c'était très chaleureux.",
        ],
        "de": [
            "Noor hat uns sehr herzlich empfangen.",
            "Wir haben uns vom ersten Moment an willkommen gefühlt.",
            "Die Familie war unglaublich gastfreundlich.",
            "Ein so warmherziger Empfang, alle haben gelächelt.",
            "Danke für die tolle Gastfreundschaft.",
            "Sehr freundliche Gastgeberin, wir fühlten uns wie zu Hause.",
            "herzlicher empfang!",
            "Man hat uns wie Freunde aufgenommen, das hat uns wirklich berührt.",
            "Die Leute auf der Farm waren total nett zu uns.",
        ],
        "es": [
            "Noor nos recibió con muchísimo cariño.",
            "Nos sentimos bienvenidos desde que llegamos.",
            "Una acogida muy cálida, toda la familia sonriendo.",
            "Gracias por la hospitalidad, fueron muy amables.",
            "La anfitriona fue encantadora, nos sentimos como en casa.",
            "muy buena acogida",
            "La familia nos recibió como amigos y eso nos emocionó.",
            "Gente muy amable y acogedora.",
            "El recibimiento fue precioso, muy cercano.",
        ],
    },
    "P2": {  # Visite du champ et des caféiers intéressante
        "en": [
            "Walking through the coffee plants was fascinating.",
            "I loved seeing the coffee trees up close in the field.",
            "The tour of the plantation was really interesting.",
            "Seeing the red cherries on the bushes was amazing.",
            "The walk in the fields, the coffee on the slope, the beans and maize below, all very interesting.",
            "nice field tour",
            "We enjoyed the visit of the coffee plot a lot.",
            "It was great to see where the coffee actually grows.",
            "The part where we went among the coffee trees was my favourite.",
        ],
        "fr": [
            "La balade au milieu des caféiers était passionnante.",
            "J'ai adoré voir les plants de café de près dans le champ.",
            "La visite de la plantation était vraiment intéressante.",
            "Voir les cerises rouges sur les caféiers, c'était génial.",
            "Le tour des champs, le café en haut et le maïs en bas, très intéressant.",
            "visite des champs top",
            "On a beaucoup aimé la visite de la parcelle de café.",
            "C'était super de voir où pousse vraiment le café.",
            "Le moment dans les caféiers, c'était mon préféré.",
        ],
        "de": [
            "Der Rundgang durch die Kaffeepflanzen war faszinierend.",
            "Ich fand es toll, die Kaffeesträucher auf dem Feld aus der Nähe zu sehen.",
            "Die Führung über die Plantage war sehr interessant.",
            "Die roten Kaffeekirschen an den Sträuchern zu sehen war großartig.",
            "Der Gang über die Felder, oben der Kaffee, unten Mais und Bohnen, wirklich spannend.",
            "schöne feldführung",
            "Der Besuch im Kaffeegarten hat uns sehr gefallen.",
            "Es war super zu sehen, wo der Kaffee wirklich wächst.",
            "Der Teil zwischen den Kaffeebäumen war mein Lieblingsmoment.",
        ],
        "es": [
            "El paseo entre los cafetos fue fascinante.",
            "Me encantó ver las plantas de café de cerca en el campo.",
            "La visita a la plantación fue muy interesante.",
            "Ver las cerezas rojas en los arbustos fue increíble.",
            "El recorrido por los campos, el café arriba y el maíz abajo, muy interesante.",
            "buen recorrido por el campo",
            "Nos gustó mucho visitar la parcela de café.",
            "Fue genial ver dónde crece de verdad el café.",
            "La parte entre los cafetales fue mi favorita.",
        ],
    },
    "P3": {  # Torréfaction ou dégustation appréciée
        "en": [
            "Roasting the beans ourselves was the highlight.",
            "The coffee tasting was excellent.",
            "I loved roasting coffee over the fire with Noor.",
            "That cup of freshly roasted coffee was the best I've ever had.",
            "The smell when the beans were roasting, wonderful.",
            "loved the tasting",
            "We really enjoyed grinding and tasting the coffee at the end.",
            "The roasting session was so much fun.",
            "Tasting her own coffee straight from the pan was special.",
        ],
        "fr": [
            "Torréfier les grains nous-mêmes, c'était le meilleur moment.",
            "La dégustation de café était excellente.",
            "J'ai adoré griller le café sur le feu avec Noor.",
            "Ce café fraîchement torréfié, le meilleur de ma vie.",
            "L'odeur des grains en train de griller, magnifique.",
            "dégustation géniale",
            "On a adoré moudre et goûter le café à la fin.",
            "La torréfaction était vraiment amusante.",
            "Goûter son propre café juste sorti de la poêle, c'était spécial.",
        ],
        "de": [
            "Die Bohnen selbst zu rösten war das Highlight.",
            "Die Kaffeeverkostung war ausgezeichnet.",
            "Ich fand es toll, mit Noor Kaffee über dem Feuer zu rösten.",
            "Der frisch geröstete Kaffee war der beste, den ich je getrunken habe.",
            "Der Duft beim Rösten der Bohnen, herrlich.",
            "tolle verkostung",
            "Das Mahlen und Probieren am Ende hat uns sehr gefallen.",
            "Das Rösten hat richtig Spaß gemacht.",
            "Ihren eigenen Kaffee direkt aus der Pfanne zu probieren war etwas Besonderes.",
        ],
        "es": [
            "Tostar los granos nosotros mismos fue lo mejor.",
            "La cata de café fue excelente.",
            "Me encantó tostar el café al fuego con Noor.",
            "Ese café recién tostado fue el mejor de mi vida.",
            "El olor de los granos tostándose, maravilloso.",
            "la degustación genial",
            "Nos encantó moler y probar el café al final.",
            "El tostado fue muy divertido.",
            "Probar su propio café recién salido de la sartén fue especial.",
        ],
    },
    "P4": {  # Repas apprécié
        "en": [
            "The lunch was delicious.",
            "We loved the meal Noor cooked for us.",
            "The beans and plantains were so tasty.",
            "Great food, generous and homemade.",
            "Lunch with the family was one of the best parts, the food was amazing.",
            "yummy lunch",
            "The meal was simple but really good.",
            "Thank you for the delicious food.",
            "I'd come back just for that lunch.",
        ],
        "fr": [
            "Le repas était délicieux.",
            "On a adoré le déjeuner préparé par Noor.",
            "Les haricots et les bananes plantains étaient excellents.",
            "Très bonne cuisine maison et copieuse.",
            "Le repas en famille, un des meilleurs moments, c'était vraiment bon.",
            "repas trop bon",
            "Un repas simple mais vraiment savoureux.",
            "Merci pour ce bon déjeuner.",
            "Je reviendrais rien que pour le repas.",
        ],
        "de": [
            "Das Mittagessen war köstlich.",
            "Das Essen, das Noor für uns gekocht hat, war super.",
            "Die Bohnen und Kochbananen waren sehr lecker.",
            "Tolles Essen, reichlich und hausgemacht.",
            "Das Essen mit der Familie war einer der schönsten Momente, sehr lecker.",
            "leckeres essen",
            "Einfaches Essen, aber richtig gut.",
            "Danke für das leckere Mittagessen.",
            "Allein für das Essen würde ich wiederkommen.",
        ],
        "es": [
            "La comida estaba deliciosa.",
            "Nos encantó el almuerzo que cocinó Noor.",
            "Los frijoles y los plátanos estaban riquísimos.",
            "Muy buena comida casera y abundante.",
            "Comer con la familia fue de lo mejor, la comida increíble.",
            "almuerzo muy rico",
            "Una comida sencilla pero muy sabrosa.",
            "Gracias por la comida tan rica.",
            "Volvería solo por ese almuerzo.",
        ],
    },
    "P5": {  # Explications claires sur le café et la ferme
        "en": [
            "Noor explained every step of coffee making very clearly.",
            "I finally understand how coffee goes from cherry to cup.",
            "The explanations about the farm were clear and easy to follow.",
            "We learned so much about how the cooperative works.",
            "She showed us the drying and washing and explained why each step matters.",
            "very informative",
            "Really clear explanations, even the kids understood.",
            "Learned a lot about growing coffee.",
            "Everything about the farm and the harvest was explained well.",
        ],
        "fr": [
            "Noor a expliqué chaque étape du café très clairement.",
            "Je comprends enfin comment on passe de la cerise à la tasse.",
            "Les explications sur la ferme étaient claires et faciles à suivre.",
            "On a appris plein de choses sur le fonctionnement de la coopérative.",
            "Elle nous a montré le lavage et le séchage en expliquant à quoi sert chaque étape.",
            "très instructif",
            "Des explications vraiment claires, même les enfants ont compris.",
            "J'ai appris beaucoup sur la culture du café.",
            "Tout était bien expliqué sur la ferme et la récolte.",
        ],
        "de": [
            "Noor hat jeden Schritt der Kaffeeherstellung sehr klar erklärt.",
            "Jetzt verstehe ich endlich, wie aus der Kirsche Kaffee wird.",
            "Die Erklärungen zur Farm waren klar und leicht verständlich.",
            "Wir haben viel darüber gelernt, wie die Kooperative funktioniert.",
            "Sie hat uns Waschen und Trocknen gezeigt und erklärt, wofür jeder Schritt gut ist.",
            "sehr lehrreich",
            "Wirklich verständliche Erklärungen, sogar die Kinder haben alles verstanden.",
            "Ich habe viel über den Kaffeeanbau gelernt.",
            "Alles über die Farm und die Ernte wurde gut erklärt.",
        ],
        "es": [
            "Noor explicó cada paso del café con mucha claridad.",
            "Por fin entiendo cómo se pasa de la cereza a la taza.",
            "Las explicaciones sobre la finca fueron claras y fáciles de seguir.",
            "Aprendimos mucho sobre cómo funciona la cooperativa.",
            "Nos enseñó el lavado y el secado y explicó para qué sirve cada paso.",
            "muy instructivo",
            "Explicaciones muy claras, hasta los niños lo entendieron.",
            "Aprendí muchísimo sobre el cultivo del café.",
            "Todo sobre la finca y la cosecha estuvo bien explicado.",
        ],
    },
    "P6": {  # Expérience authentique, vie de la ferme
        "en": [
            "It felt so authentic, nothing staged for tourists.",
            "We got to see real everyday life on the farm.",
            "A genuine experience, not a tourist trap.",
            "Helping with the chores and meeting the kids made it feel real.",
            "Seeing how a farming family really lives was eye-opening and very authentic.",
            "so authentic",
            "This was real rural life, not a show.",
            "Loved sharing a day of farm life with them.",
            "It felt like we were part of the family's daily routine.",
        ],
        "fr": [
            "C'était très authentique, rien de fait pour les touristes.",
            "On a vu la vraie vie de tous les jours à la ferme.",
            "Une expérience vraie, pas un piège à touristes.",
            "Aider aux tâches et rencontrer les enfants, ça rendait tout très réel.",
            "Voir comment vit vraiment une famille d'agriculteurs, c'était authentique et marquant.",
            "trop authentique",
            "C'était la vraie vie rurale, pas un spectacle.",
            "J'ai adoré partager une journée de la vie de la ferme.",
            "On avait l'impression de faire partie du quotidien de la famille.",
        ],
        "de": [
            "Es war so authentisch, nichts für Touristen inszeniert.",
            "Wir haben das echte Alltagsleben auf dem Hof gesehen.",
            "Ein echtes Erlebnis, keine Touristenfalle.",
            "Bei der Arbeit mitzuhelfen und die Kinder kennenzulernen machte es echt.",
            "Zu sehen, wie eine Bauernfamilie wirklich lebt, war sehr authentisch und beeindruckend.",
            "total authentisch",
            "Das war echtes Landleben, keine Show.",
            "Ich habe es geliebt, einen Tag Hofleben mit ihnen zu teilen.",
            "Wir fühlten uns wie ein Teil des Familienalltags.",
        ],
        "es": [
            "Fue muy auténtico, nada montado para turistas.",
            "Vimos la vida real de cada día en la finca.",
            "Una experiencia genuina, no una trampa para turistas.",
            "Ayudar con las tareas y conocer a los niños lo hizo muy real.",
            "Ver cómo vive de verdad una familia campesina fue muy auténtico y nos marcó.",
            "súper auténtico",
            "Era la vida rural de verdad, no un espectáculo.",
            "Me encantó compartir un día de la vida en la granja.",
            "Sentimos que éramos parte del día a día de la familia.",
        ],
    },
    "P7": {  # Paysage, cadre
        "en": [
            "The view over the hills was breathtaking.",
            "Such a beautiful landscape.",
            "The setting of the farm on the hillside is stunning.",
            "Green hills everywhere, the scenery was incredible.",
            "From the top of the coffee field you can see the whole valley, absolutely gorgeous.",
            "amazing views",
            "Very peaceful place, lovely surroundings.",
            "The mist on the hills in the morning was magical.",
            "What a beautiful spot.",
        ],
        "fr": [
            "La vue sur les collines était à couper le souffle.",
            "Quel paysage magnifique.",
            "Le cadre de la ferme à flanc de colline est superbe.",
            "Des collines vertes partout, le décor était incroyable.",
            "Du haut du champ de café on voit toute la vallée, c'est splendide.",
            "vue magnifique",
            "Un endroit très paisible, un cadre superbe.",
            "La brume sur les collines le matin, c'était magique.",
            "Quel bel endroit.",
        ],
        "de": [
            "Der Blick über die Hügel war atemberaubend.",
            "Was für eine wunderschöne Landschaft.",
            "Die Lage der Farm am Hang ist traumhaft.",
            "Überall grüne Hügel, die Kulisse war unglaublich.",
            "Von oben am Kaffeefeld sieht man das ganze Tal, einfach herrlich.",
            "tolle aussicht",
            "Ein sehr ruhiger Ort mit schöner Umgebung.",
            "Der Nebel über den Hügeln am Morgen war magisch.",
            "Was für ein schöner Ort.",
        ],
        "es": [
            "La vista sobre las colinas era impresionante.",
            "Qué paisaje tan bonito.",
            "El entorno de la finca en la ladera es precioso.",
            "Colinas verdes por todas partes, el paisaje era increíble.",
            "Desde arriba del cafetal se ve todo el valle, una maravilla.",
            "vistas increíbles",
            "Un lugar muy tranquilo, un entorno precioso.",
            "La niebla sobre las colinas por la mañana fue mágica.",
            "Qué sitio tan bonito.",
        ],
    },
    "P8": {  # Bon rapport qualité-prix
        "en": [
            "Great value for money.",
            "Totally worth the price.",
            "Very reasonable price for everything we got.",
            "For what we paid, it was excellent value.",
            "Honestly cheap for a whole morning with lunch and tasting included.",
            "worth every franc",
            "Fair price, we'd happily have paid more.",
            "Good value compared to the big tours.",
            "The price was more than fair.",
        ],
        "fr": [
            "Très bon rapport qualité-prix.",
            "Ça valait largement le prix.",
            "Un prix très raisonnable pour tout ce qu'on a eu.",
            "Pour ce qu'on a payé, c'était vraiment une bonne affaire.",
            "Franchement pas cher pour une matinée entière avec repas et dégustation.",
            "vaut chaque franc",
            "Prix juste, on aurait volontiers payé plus.",
            "Bon rapport qualité-prix comparé aux grands circuits.",
            "Le tarif était plus que correct.",
        ],
        "de": [
            "Sehr gutes Preis-Leistungs-Verhältnis.",
            "Absolut den Preis wert.",
            "Ein sehr fairer Preis für alles, was wir bekommen haben.",
            "Für das, was wir bezahlt haben, war es top.",
            "Ehrlich gesagt günstig für einen ganzen Vormittag mit Essen und Verkostung.",
            "jeden franc wert",
            "Fairer Preis, wir hätten gern mehr bezahlt.",
            "Viel besser im Preis als die großen Touren.",
            "Der Preis war mehr als angemessen.",
        ],
        "es": [
            "Muy buena relación calidad-precio.",
            "Valió totalmente lo que costó.",
            "Un precio muy razonable para todo lo que recibimos.",
            "Por lo que pagamos, fue una ganga.",
            "Sinceramente barato para una mañana entera con comida y cata incluidas.",
            "vale cada franco",
            "Precio justo, habríamos pagado más con gusto.",
            "Buena relación calidad-precio comparado con los grandes tours.",
            "El precio fue más que correcto.",
        ],
    },
    "P9": {  # Envie d'acheter du café
        "en": [
            "I'd love to buy some of her coffee.",
            "Can we order coffee from the farm?",
            "I want to take a bag of this coffee home.",
            "Please sell your coffee, I would buy several kilos.",
            "I wish I could buy beans from Noor to bring back to my friends.",
            "want to buy coffee!",
            "Where can I buy this coffee?",
            "I'd buy her roasted coffee in a heartbeat.",
            "We would like to purchase a few packets before we leave.",
        ],
        "fr": [
            "J'aimerais beaucoup acheter de son café.",
            "Est-ce qu'on peut commander du café de la ferme ?",
            "Je veux rapporter un sachet de ce café à la maison.",
            "Vendez votre café, j'en achèterais plusieurs kilos.",
            "J'aimerais acheter des grains à Noor pour en ramener à mes amis.",
            "envie d'acheter du café",
            "Où est-ce qu'on peut acheter ce café ?",
            "J'achèterais son café torréfié sans hésiter.",
            "On voudrait acheter quelques paquets avant de partir.",
        ],
        "de": [
            "Ich würde sehr gern etwas von ihrem Kaffee kaufen.",
            "Kann man Kaffee von der Farm bestellen?",
            "Ich möchte eine Tüte von diesem Kaffee mit nach Hause nehmen.",
            "Bitte verkauft euren Kaffee, ich würde mehrere Kilo nehmen.",
            "Ich würde Noor gern Bohnen abkaufen, um sie meinen Freunden mitzubringen.",
            "will kaffee kaufen!",
            "Wo kann ich diesen Kaffee kaufen?",
            "Ihren gerösteten Kaffee würde ich sofort kaufen.",
            "Wir würden gern ein paar Päckchen kaufen, bevor wir fahren.",
        ],
        "es": [
            "Me encantaría comprar un poco de su café.",
            "¿Se puede pedir café de la finca?",
            "Quiero llevarme una bolsa de este café a casa.",
            "Vendan su café, yo compraría varios kilos.",
            "Me gustaría comprarle granos a Noor para llevar a mis amigos.",
            "quiero comprar café",
            "¿Dónde puedo comprar este café?",
            "Compraría su café tostado sin dudarlo.",
            "Nos gustaría comprar unos paquetes antes de irnos.",
        ],
    },
    "P10": {  # Envie de revenir ou de recommander
        "en": [
            "We will definitely come back.",
            "I'll recommend this farm to all my friends.",
            "We'd love to return next year with the kids.",
            "I'm telling everyone back home to visit.",
            "If we ever come back to the country, we'll book this visit again for sure.",
            "will recommend!",
            "A must-do, I'd recommend it to anyone travelling here.",
            "Hope to come back during the harvest.",
            "We'll send our friends your way.",
        ],
        "fr": [
            "On reviendra, c'est sûr.",
            "Je vais recommander cette ferme à tous mes amis.",
            "On aimerait revenir l'année prochaine avec les enfants.",
            "Je vais dire à tout le monde chez moi de venir.",
            "Si on revient dans le pays, on refera cette visite sans hésiter.",
            "je recommande !",
            "À faire absolument, je la conseille à tous les voyageurs.",
            "J'espère revenir pendant la récolte.",
            "On vous enverra nos amis.",
        ],
        "de": [
            "Wir kommen auf jeden Fall wieder.",
            "Ich werde diese Farm allen meinen Freunden empfehlen.",
            "Wir würden nächstes Jahr gern mit den Kindern wiederkommen.",
            "Ich erzähle zu Hause allen, dass sie herkommen sollen.",
            "Wenn wir wieder im Land sind, buchen wir diesen Besuch auf jeden Fall noch einmal.",
            "klare empfehlung!",
            "Ein Muss, ich empfehle es jedem, der hier reist.",
            "Ich hoffe, zur Erntezeit wiederzukommen.",
            "Wir schicken euch unsere Freunde vorbei.",
        ],
        "es": [
            "Volveremos seguro.",
            "Voy a recomendar esta finca a todos mis amigos.",
            "Nos encantaría volver el año que viene con los niños.",
            "Le diré a todo el mundo en casa que venga.",
            "Si volvemos al país, repetiremos esta visita sin duda.",
            "¡lo recomiendo!",
            "Imprescindible, se lo recomendaría a cualquiera que viaje por aquí.",
            "Espero volver durante la cosecha.",
            "Les mandaremos a nuestros amigos.",
        ],
    },
    "P11": {  # Satisfaction générale
        "en": [
            "Thank you, it was great!",
            "We had a wonderful time.",
            "Amazing day, thanks so much.",
            "Really enjoyed everything.",
            "Thanks for everything, it was one of the best days of our trip.",
            "perfect, thank you",
            "What a lovely experience overall.",
            "It was super, thanks a lot.",
            "Everything was great, thank you Noor.",
        ],
        "fr": [
            "Merci, c'était super !",
            "On a passé un moment merveilleux.",
            "Journée géniale, merci beaucoup.",
            "On a vraiment tout aimé.",
            "Merci pour tout, une des plus belles journées de notre voyage.",
            "parfait, merci",
            "Quelle belle expérience dans l'ensemble.",
            "C'était top, merci mille fois.",
            "Tout était génial, merci Noor.",
        ],
        "de": [
            "Danke, es war super!",
            "Wir hatten eine wunderbare Zeit.",
            "Toller Tag, vielen Dank.",
            "Uns hat wirklich alles gefallen.",
            "Danke für alles, einer der schönsten Tage unserer Reise.",
            "perfekt, danke",
            "Insgesamt ein wunderschönes Erlebnis.",
            "Es war klasse, vielen Dank.",
            "Alles war großartig, danke Noor.",
        ],
        "es": [
            "¡Gracias, fue genial!",
            "Lo pasamos de maravilla.",
            "Un día increíble, muchas gracias.",
            "Nos gustó todo de verdad.",
            "Gracias por todo, uno de los mejores días del viaje.",
            "perfecto, gracias",
            "Qué experiencia tan bonita en general.",
            "Fue estupendo, mil gracias.",
            "Todo estuvo genial, gracias Noor.",
        ],
    },
}
