# Formulations d'exemple SYNTHÉTIQUES supplémentaires (tâche echo-recall, 2026-10-04) : 6 par constat et par langue.
# Rédigées à partir de la définition de chaque constat (intitulés et règles de distinction du catalog/README.md),
# jamais à partir du corpus d'évaluation (eval/data/feedback.jsonl) ; eval/data/check_disjoint.py le vérifie.
# Règle du cœur respectée : un exemple formule le constat lui-même, jamais sa version inversée par une négation.
# Les constats positifs n'ont aucun exemple contenant un marqueur de négation (sinon une négation qui annule un
# constat positif, « la dégustation n'était pas bonne », trouverait des exemples niés du même constat).
# Les constats négatifs dont la formulation naturelle est niée (« pas assez à manger », « on n'a pas pu acheter »)
# en ont quelques-uns, comme les exemples d'origine.

EXTRA_EXAMPLES = {
    "P1": {
        "en": [
            "From the first minute the family made us feel at ease.",
            "What a warm greeting when we got out of the car.",
            "Our hosts were so welcoming and kind.",
            "lovely hosts",
            "They greeted us with big smiles and a handshake for everyone.",
            "We were made to feel like guests of honour.",
        ],
        "fr": [
            "Dès la première minute, la famille nous a mis à l'aise.",
            "Quel accueil chaleureux à notre arrivée !",
            "Nos hôtes étaient adorables et très attentionnés.",
            "hôtes très accueillants",
            "Ils nous ont salués avec de grands sourires.",
            "On s'est sentis attendus et bien reçus.",
        ],
        "de": [
            "Vom ersten Augenblick an hat die Familie uns herzlich aufgenommen.",
            "Was für eine warme Begrüßung bei unserer Ankunft.",
            "Unsere Gastgeber waren so freundlich und aufmerksam.",
            "liebe gastgeber",
            "Sie haben uns mit einem breiten Lächeln begrüßt.",
            "Wir wurden empfangen wie Ehrengäste.",
        ],
        "es": [
            "Desde el primer minuto la familia nos hizo sentir a gusto.",
            "¡Qué recibimiento tan cálido al llegar!",
            "Los anfitriones fueron atentos y cariñosos.",
            "anfitriones encantadores",
            "Nos saludaron con una gran sonrisa a todos.",
            "Nos trataron como invitados de honor.",
        ],
    },
    "P2": {
        "en": [
            "Walking between the rows of coffee bushes was really interesting.",
            "We saw how the coffee plants grow on the hillside, fascinating.",
            "The plantation walk was a highlight for me.",
            "great walk through the coffee field",
            "Seeing the young coffee seedlings and the old trees side by side was interesting.",
            "We loved wandering among the coffee trees.",
        ],
        "fr": [
            "La promenade entre les rangées de caféiers était passionnante.",
            "Voir les plants de café pousser sur la colline, c'était très intéressant.",
            "La balade dans la plantation a été un moment fort.",
            "belle visite des caféiers",
            "Voir les jeunes plants et les vieux caféiers côte à côte, c'était intéressant.",
            "On a adoré se promener au milieu des caféiers.",
        ],
        "de": [
            "Der Spaziergang zwischen den Kaffeesträuchern war spannend.",
            "Zu sehen, wie die Kaffeepflanzen am Hang wachsen, war faszinierend.",
            "Der Rundgang über die Plantage war für mich ein Höhepunkt.",
            "toller rundgang im kaffeefeld",
            "Die jungen Setzlinge neben den alten Kaffeebäumen zu sehen war interessant.",
            "Wir sind gern zwischen den Kaffeebäumen herumgelaufen.",
        ],
        "es": [
            "El paseo entre las filas de cafetos fue muy interesante.",
            "Ver cómo crecen las plantas de café en la ladera fue fascinante.",
            "El recorrido por la plantación fue lo mejor para mí.",
            "buen paseo por el cafetal",
            "Ver los plantones jóvenes junto a los cafetos viejos fue interesante.",
            "Nos encantó caminar entre los cafetos.",
        ],
    },
    "P3": {
        "en": [
            "Watching the beans turn brown in the pan was great.",
            "The cup we drank after roasting was delicious.",
            "The little coffee ceremony after roasting was lovely.",
            "roasting was fun",
            "Grinding the beans by hand and then tasting the coffee was a great moment.",
            "Their coffee tastes amazing, so smooth.",
        ],
        "fr": [
            "Voir les grains brunir dans la poêle, c'était génial.",
            "La tasse bue après la torréfaction était délicieuse.",
            "On a adoré le moment du café à la fin.",
            "super torréfaction",
            "Moudre les grains à la main puis goûter le café, un vrai plaisir.",
            "Leur café est délicieux, très doux.",
        ],
        "de": [
            "Zuzusehen, wie die Bohnen in der Pfanne braun werden, war toll.",
            "Die Tasse nach dem Rösten war köstlich.",
            "Die Kaffeezeremonie am Ende hat uns sehr gefallen.",
            "rösten hat spaß gemacht",
            "Die Bohnen von Hand mahlen und dann den Kaffee probieren, ein schöner Moment.",
            "Ihr Kaffee schmeckt wunderbar, ganz mild.",
        ],
        "es": [
            "Ver cómo los granos se tostaban en la sartén fue genial.",
            "La taza que tomamos después del tostado estaba riquísima.",
            "Nos encantó la ceremonia del café al final.",
            "el tostado fue divertido",
            "Moler los granos a mano y luego probar el café fue un gran momento.",
            "Su café sabe buenísimo, muy suave.",
        ],
    },
    "P4": {
        "en": [
            "The home-cooked lunch was a real treat.",
            "Everything on the plate was fresh and full of flavour.",
            "We ate so well, thank you to the cook.",
            "delicious food",
            "Sharing a local meal with the family was wonderful, especially the sweet potatoes.",
            "The food was excellent.",
        ],
        "fr": [
            "Le déjeuner fait maison était un régal.",
            "Tout dans l'assiette était frais et savoureux.",
            "On a très bien mangé, merci à la cuisinière.",
            "super bon déjeuner",
            "Partager un repas local avec la famille, c'était merveilleux, surtout les patates douces.",
            "La cuisine était excellente.",
        ],
        "de": [
            "Das hausgemachte Mittagessen war ein Genuss.",
            "Alles auf dem Teller war frisch und lecker.",
            "Wir haben so gut gegessen, danke an die Köchin.",
            "sehr leckeres essen",
            "Ein einheimisches Essen mit der Familie zu teilen war wunderbar, vor allem die Süßkartoffeln.",
            "Das Essen war ausgezeichnet.",
        ],
        "es": [
            "El almuerzo casero fue una delicia.",
            "Todo en el plato estaba fresco y sabroso.",
            "Comimos muy bien, gracias a la cocinera.",
            "comida riquísima",
            "Compartir una comida local con la familia fue precioso, sobre todo las batatas.",
            "La comida estaba excelente.",
        ],
    },
    "P5": {
        "en": [
            "She explained the whole process from seed to cup in simple words.",
            "Every question we asked got a clear answer.",
            "Now I know why coffee beans are washed and dried.",
            "great explanations",
            "The explanations about fermentation and drying were detailed but easy to understand.",
            "We learned how the farm and the cooperative work together.",
        ],
        "fr": [
            "Elle a expliqué tout le processus, de la graine à la tasse, avec des mots simples.",
            "Chaque question a reçu une réponse claire.",
            "Maintenant je sais pourquoi on lave et on sèche les grains.",
            "très bonnes explications",
            "Les explications sur la fermentation et le séchage étaient précises et faciles à suivre.",
            "On a appris comment la ferme travaille avec la coopérative.",
        ],
        "de": [
            "Sie hat den ganzen Weg von der Bohne bis zur Tasse einfach erklärt.",
            "Jede Frage wurde klar beantwortet.",
            "Jetzt weiß ich, warum die Kaffeebohnen gewaschen und getrocknet werden.",
            "super erklärungen",
            "Die Erklärungen zur Fermentation und Trocknung waren genau und leicht verständlich.",
            "Wir haben gelernt, wie der Hof mit der Genossenschaft zusammenarbeitet.",
        ],
        "es": [
            "Explicó todo el proceso, de la semilla a la taza, con palabras sencillas.",
            "Cada pregunta tuvo una respuesta clara.",
            "Ahora sé por qué se lavan y se secan los granos.",
            "muy buenas explicaciones",
            "Las explicaciones sobre la fermentación y el secado fueron detalladas y fáciles de entender.",
            "Aprendimos cómo trabaja la finca con la cooperativa.",
        ],
    },
    "P6": {
        "en": [
            "It felt like a real day in a farming family's life.",
            "Everything was genuine and simple, exactly what we hoped for.",
            "We shared their daily life for a few hours, very real.",
            "real farm life",
            "Milking the cow and carrying water with the children gave us a true taste of rural life.",
            "A truly authentic visit.",
        ],
        "fr": [
            "On avait l'impression de vivre une vraie journée de paysans.",
            "Tout était simple et vrai, exactement ce qu'on espérait.",
            "On a partagé leur quotidien pendant quelques heures, très authentique.",
            "vraie vie de ferme",
            "Traire la vache et porter l'eau avec les enfants, c'était la vraie vie rurale.",
            "Une visite vraiment authentique.",
        ],
        "de": [
            "Es fühlte sich an wie ein echter Tag im Leben einer Bauernfamilie.",
            "Alles war einfach und echt, genau wie erhofft.",
            "Wir haben ein paar Stunden ihren Alltag geteilt, sehr authentisch.",
            "echtes landleben",
            "Mit den Kindern die Kuh melken und Wasser tragen, das war echtes Landleben.",
            "Ein wirklich authentischer Besuch.",
        ],
        "es": [
            "Se sentía como un día de verdad en la vida de una familia campesina.",
            "Todo era sencillo y auténtico, justo lo que esperábamos.",
            "Compartimos su día a día durante unas horas, muy real.",
            "vida de campo auténtica",
            "Ordeñar la vaca y cargar agua con los niños fue vivir de verdad la vida rural.",
            "Una visita de lo más auténtica.",
        ],
    },
    "P7": {
        "en": [
            "The hills around the farm are gorgeous.",
            "We took so many photos of the valley.",
            "Beautiful countryside, green as far as you can see.",
            "stunning scenery",
            "Sitting under the banana trees looking at the volcanoes in the distance was unforgettable.",
            "The farm is in a magnificent spot.",
        ],
        "fr": [
            "Les collines autour de la ferme sont magnifiques.",
            "On a pris plein de photos de la vallée.",
            "Une campagne superbe, verte à perte de vue.",
            "paysages sublimes",
            "Assis sous les bananiers, avec les volcans au loin, c'était inoubliable.",
            "La ferme est dans un endroit magnifique.",
        ],
        "de": [
            "Die Hügel rund um die Farm sind wunderschön.",
            "Wir haben so viele Fotos vom Tal gemacht.",
            "Herrliche Landschaft, grün so weit das Auge reicht.",
            "atemberaubende landschaft",
            "Unter den Bananenstauden zu sitzen und in der Ferne die Vulkane zu sehen, war unvergesslich.",
            "Die Farm liegt an einem traumhaften Ort.",
        ],
        "es": [
            "Las colinas alrededor de la finca son preciosas.",
            "Hicimos muchísimas fotos del valle.",
            "Un campo precioso, verde hasta donde alcanza la vista.",
            "vistas espectaculares",
            "Sentarse bajo los bananos mirando los volcanes a lo lejos fue inolvidable.",
            "La finca está en un lugar magnífico.",
        ],
    },
    "P8": {
        "en": [
            "The price was very fair for such a full visit.",
            "Good value, cheaper than we expected.",
            "We got a lot for what we paid.",
            "fair price",
            "For the price of a restaurant meal we had the visit, a tasting and lunch, a great deal.",
            "Well worth the money.",
        ],
        "fr": [
            "Le prix était très correct pour une visite aussi complète.",
            "Bon rapport qualité-prix, moins cher que prévu.",
            "On en a eu beaucoup pour notre argent.",
            "prix juste",
            "Pour le prix d'un repas au restaurant, on a eu la visite, la dégustation et le déjeuner, une affaire.",
            "Ça vaut largement son prix.",
        ],
        "de": [
            "Der Preis war für so einen vollen Besuch sehr fair.",
            "Gutes Preis-Leistungs-Verhältnis, günstiger als erwartet.",
            "Wir haben viel für unser Geld bekommen.",
            "fairer preis",
            "Für den Preis eines Restaurantessens gab es Besuch, Verkostung und Mittagessen, ein gutes Angebot.",
            "Das Geld absolut wert.",
        ],
        "es": [
            "El precio fue muy justo para una visita tan completa.",
            "Buena relación calidad-precio, más barato de lo esperado.",
            "Recibimos mucho por lo que pagamos.",
            "precio justo",
            "Por lo que cuesta una comida en un restaurante tuvimos la visita, la cata y el almuerzo, una ganga.",
            "Vale totalmente lo que cuesta.",
        ],
    },
    "P9": {
        "en": [
            "Is it possible to buy a kilo of your beans?",
            "I'd happily pay for a few bags to take back.",
            "Do you ship coffee abroad? I'd order some.",
            "i want some of that coffee to take home",
            "Please let us know how to buy your roasted coffee, my whole office would want some.",
            "Could we buy ground coffee before leaving?",
        ],
        "fr": [
            "Est-ce qu'on peut acheter un kilo de vos grains ?",
            "J'achèterais volontiers quelques sachets à ramener.",
            "Vous expédiez du café à l'étranger ? J'en commanderais.",
            "je veux ramener de ce café",
            "Dites-nous comment acheter votre café torréfié, tout mon bureau en voudra.",
            "Peut-on acheter du café moulu avant de partir ?",
        ],
        "de": [
            "Kann man ein Kilo von euren Bohnen kaufen?",
            "Ich würde gern ein paar Tüten mitnehmen und bezahlen.",
            "Verschickt ihr Kaffee ins Ausland? Ich würde bestellen.",
            "möchte kaffee mitnehmen",
            "Sagt uns bitte, wie wir euren gerösteten Kaffee kaufen können, das ganze Büro will welchen.",
            "Können wir vor der Abreise gemahlenen Kaffee kaufen?",
        ],
        "es": [
            "¿Se puede comprar un kilo de sus granos?",
            "Con gusto pagaría por unas bolsas para llevar.",
            "¿Envían café al extranjero? Yo pediría.",
            "quiero llevarme ese café",
            "Dígannos cómo comprar su café tostado, toda mi oficina querrá.",
            "¿Podemos comprar café molido antes de irnos?",
        ],
    },
    "P10": {
        "en": [
            "We'll be back for sure.",
            "Highly recommended to anyone visiting the region.",
            "I've already told my friends to book it.",
            "must come back",
            "Next time we're in the country we'll bring my parents, they'd love it.",
            "Five stars, I recommend it.",
        ],
        "fr": [
            "On reviendra avec plaisir, promis.",
            "Je recommande vivement à tous ceux qui passent dans la région.",
            "J'ai déjà dit à mes amis de réserver.",
            "à refaire",
            "La prochaine fois qu'on vient dans le pays, on amènera mes parents, ils vont adorer.",
            "Cinq étoiles, je recommande.",
        ],
        "de": [
            "Wir kommen bestimmt wieder.",
            "Sehr zu empfehlen für alle, die in der Gegend sind.",
            "Ich habe meinen Freunden schon gesagt, dass sie buchen sollen.",
            "klare empfehlung",
            "Wenn wir wieder im Land sind, bringen wir meine Eltern mit, die würden es lieben.",
            "Fünf Sterne, sehr empfehlenswert.",
        ],
        "es": [
            "Volveremos con muchas ganas.",
            "Muy recomendable para quien visite la región.",
            "Ya les dije a mis amigos que reserven.",
            "para repetir",
            "La próxima vez que vengamos al país traeremos a mis padres, les encantará.",
            "Cinco estrellas, lo recomiendo.",
        ],
    },
    "P11": {
        "en": [
            "A really good day, thank you all.",
            "We loved it, thanks again.",
            "Great experience from start to finish.",
            "all good, thanks",
            "It was a beautiful morning and we are very happy we came.",
            "Really nice visit, many thanks.",
        ],
        "fr": [
            "Une très belle journée, merci à tous.",
            "On a adoré, encore merci.",
            "Super expérience du début à la fin.",
            "tout était top, merci",
            "C'était une belle matinée et on est très contents d'être venus.",
            "Très chouette visite, merci beaucoup.",
        ],
        "de": [
            "Ein richtig schöner Tag, danke euch allen.",
            "Hat uns sehr gefallen, nochmals danke.",
            "Tolles Erlebnis von Anfang bis Ende.",
            "alles super, danke",
            "Es war ein schöner Vormittag und wir sind sehr froh, dass wir gekommen sind.",
            "Sehr schöner Besuch, vielen Dank.",
        ],
        "es": [
            "Un día muy bonito, gracias a todos.",
            "Nos encantó, gracias otra vez.",
            "Una experiencia estupenda de principio a fin.",
            "todo genial, gracias",
            "Fue una mañana preciosa y estamos muy contentos de haber venido.",
            "Muy buena visita, muchas gracias.",
        ],
    },
    "N1": {
        "en": [
            "The last part of the road is in very bad condition.",
            "Finding the entrance was a real challenge.",
            "The climb to the farm is too steep for elderly visitors.",
            "hard to get to",
            "Our driver had to stop twice to ask for directions, and the track was full of potholes.",
            "There is no clear sign to the farm from the village.",
        ],
        "fr": [
            "La fin de la route est en très mauvais état.",
            "Trouver l'entrée a été un vrai défi.",
            "La montée jusqu'à la ferme est trop raide pour les personnes âgées.",
            "difficile d'accès",
            "Notre chauffeur a dû s'arrêter deux fois pour demander son chemin, et la piste était pleine de trous.",
            "Aucun panneau n'indique la ferme depuis le village.",
        ],
        "de": [
            "Das letzte Stück der Straße ist in sehr schlechtem Zustand.",
            "Den Eingang zu finden war eine echte Herausforderung.",
            "Der Aufstieg zur Farm ist für ältere Leute zu steil.",
            "schwer zu erreichen",
            "Unser Fahrer musste zweimal nach dem Weg fragen, und die Piste war voller Schlaglöcher.",
            "Vom Dorf aus gibt es kein Schild zur Farm.",
        ],
        "es": [
            "El último tramo del camino está en muy mal estado.",
            "Encontrar la entrada fue todo un reto.",
            "La subida a la finca es demasiado empinada para personas mayores.",
            "difícil de llegar",
            "Nuestro conductor tuvo que parar dos veces a preguntar, y la pista estaba llena de baches.",
            "Desde el pueblo no hay ninguna señal hacia la finca.",
        ],
    },
    "N2": {
        "en": [
            "We weren't told the price of the tasting beforehand.",
            "The cost was a surprise when we were leaving.",
            "Nobody mentioned that lunch was extra.",
            "price not clear",
            "We had agreed on one amount by message, but on the day the total was different and nobody explained why.",
            "It would help to show the prices before the visit starts.",
        ],
        "fr": [
            "On ne nous a pas donné le prix de la dégustation à l'avance.",
            "Le prix a été une surprise au moment de partir.",
            "Personne n'a précisé que le repas était en supplément.",
            "prix pas clair",
            "On s'était mis d'accord sur un montant par message, mais le jour même le total était différent sans explication.",
            "Ce serait bien d'afficher les prix avant le début de la visite.",
        ],
        "de": [
            "Den Preis für die Verkostung hat man uns vorher nicht gesagt.",
            "Beim Gehen war der Preis eine Überraschung.",
            "Niemand hat erwähnt, dass das Mittagessen extra kostet.",
            "preis unklar",
            "Per Nachricht war ein Betrag vereinbart, am Tag selbst war die Summe anders und niemand hat es erklärt.",
            "Es wäre hilfreich, die Preise vor dem Besuch zu zeigen.",
        ],
        "es": [
            "No nos dijeron el precio de la cata antes.",
            "El precio fue una sorpresa al irnos.",
            "Nadie mencionó que el almuerzo se pagaba aparte.",
            "precio poco claro",
            "Habíamos acordado una cantidad por mensaje, pero ese día el total era otro y nadie explicó por qué.",
            "Ayudaría mostrar los precios antes de empezar la visita.",
        ],
    },
    "N3": {
        "en": [
            "It lasted much longer than announced.",
            "By the third hour we were tired of standing around.",
            "Too many long stops, it felt slow.",
            "too long for us",
            "Half a day is a lot, especially with small children, the visit should be shorter.",
            "We were exhausted, the tour could be cut down.",
        ],
        "fr": [
            "Ça a duré bien plus longtemps que prévu.",
            "À la troisième heure, on en avait assez de rester debout.",
            "Trop d'arrêts interminables, c'était lent.",
            "trop long pour nous",
            "Une demi-journée, c'est beaucoup, surtout avec de jeunes enfants, la visite devrait être plus courte.",
            "On était épuisés, la visite pourrait être raccourcie.",
        ],
        "de": [
            "Es hat viel länger gedauert als angekündigt.",
            "In der dritten Stunde hatten wir genug vom Herumstehen.",
            "Zu viele lange Stopps, es war zäh.",
            "zu lang für uns",
            "Ein halber Tag ist viel, vor allem mit kleinen Kindern, die Tour sollte kürzer sein.",
            "Wir waren erschöpft, die Tour könnte gekürzt werden.",
        ],
        "es": [
            "Duró mucho más de lo anunciado.",
            "A la tercera hora ya estábamos cansados de estar de pie.",
            "Demasiadas paradas largas, se hizo pesado.",
            "demasiado larga para nosotros",
            "Medio día es mucho, sobre todo con niños pequeños, la visita debería ser más corta.",
            "Acabamos agotados, la visita se podría acortar.",
        ],
    },
    "N4": {
        "en": [
            "It ended just as it was getting interesting.",
            "We barely had time to look around.",
            "The tour felt rushed from start to finish.",
            "too quick",
            "We travelled two hours to get there and the visit itself was over in no time, we expected more.",
            "We didn't have enough time to see everything.",
        ],
        "fr": [
            "Ça s'est terminé juste quand ça devenait intéressant.",
            "On a eu tout juste le temps de regarder autour de nous.",
            "La visite était expédiée du début à la fin.",
            "trop rapide",
            "On a fait deux heures de route pour venir et la visite était finie en un rien de temps, on s'attendait à plus.",
            "On n'a pas eu assez de temps pour tout voir.",
        ],
        "de": [
            "Es war vorbei, gerade als es spannend wurde.",
            "Wir hatten kaum Zeit, uns umzusehen.",
            "Die Tour war von Anfang bis Ende gehetzt.",
            "viel zu schnell vorbei",
            "Wir sind zwei Stunden angereist und der Besuch selbst war im Nu vorbei, wir hatten mehr erwartet.",
            "Wir hatten nicht genug Zeit, um alles zu sehen.",
        ],
        "es": [
            "Terminó justo cuando se ponía interesante.",
            "Casi no tuvimos tiempo de mirar alrededor.",
            "La visita fue con prisas de principio a fin.",
            "demasiado rápida",
            "Viajamos dos horas para llegar y la visita se acabó enseguida, esperábamos más.",
            "No tuvimos tiempo suficiente para verlo todo.",
        ],
    },
    "N5": {
        "en": [
            "We couldn't follow most of the explanations because of the language.",
            "Nobody could translate, so we just nodded along.",
            "Her English was hard to understand.",
            "communication difficult",
            "We tried with gestures and a translation app, but a lot of what she said was lost on us.",
            "Understanding each other was a struggle.",
        ],
        "fr": [
            "On n'a pas pu suivre la plupart des explications à cause de la langue.",
            "Personne ne pouvait traduire, alors on hochait la tête.",
            "Son anglais était difficile à comprendre.",
            "communication difficile",
            "On a essayé avec des gestes et une appli de traduction, mais beaucoup de choses nous ont échappé.",
            "Se comprendre était compliqué.",
        ],
        "de": [
            "Wegen der Sprache konnten wir den meisten Erklärungen nicht folgen.",
            "Niemand konnte übersetzen, also haben wir nur genickt.",
            "Ihr Englisch war schwer zu verstehen.",
            "verständigung schwierig",
            "Wir haben es mit Gesten und einer Übersetzungs-App versucht, vieles ist bei uns nicht angekommen.",
            "Sich zu verständigen war mühsam.",
        ],
        "es": [
            "No pudimos seguir casi ninguna explicación por el idioma.",
            "Nadie podía traducir, así que solo asentíamos.",
            "Su inglés era difícil de entender.",
            "comunicación difícil",
            "Intentamos con gestos y una aplicación de traducción, pero se nos escapó mucho de lo que decía.",
            "Entendernos fue complicado.",
        ],
    },
    "N6": {
        "en": [
            "We were told lunch was included but nothing came.",
            "Only a few biscuits for the whole day.",
            "The plates were half empty, we left hungry.",
            "not enough food",
            "After walking all morning we really needed a proper lunch, but there was just tea.",
            "A bigger meal would be good.",
        ],
        "fr": [
            "On nous avait dit que le déjeuner était compris, mais rien n'est venu.",
            "Juste quelques biscuits pour toute la journée.",
            "Les assiettes étaient à moitié vides, on est repartis affamés.",
            "pas assez à manger",
            "Après avoir marché toute la matinée on avait besoin d'un vrai repas, mais il n'y avait que du thé.",
            "Un repas plus copieux serait bienvenu.",
        ],
        "de": [
            "Es hieß, das Mittagessen sei inklusive, aber es kam nichts.",
            "Nur ein paar Kekse für den ganzen Tag.",
            "Die Teller waren halb leer, wir sind hungrig gegangen.",
            "zu wenig essen",
            "Nach dem Laufen den ganzen Vormittag hätten wir ein richtiges Mittagessen gebraucht, es gab nur Tee.",
            "Eine größere Mahlzeit wäre gut.",
        ],
        "es": [
            "Nos dijeron que el almuerzo estaba incluido pero no llegó nada.",
            "Solo unas galletas para todo el día.",
            "Los platos estaban medio vacíos, salimos con hambre.",
            "poca comida",
            "Después de caminar toda la mañana necesitábamos una comida de verdad, pero solo hubo té.",
            "Una comida más abundante estaría bien.",
        ],
    },
    "N7": {
        "en": [
            "The toilets were filthy.",
            "No sink or soap for washing hands.",
            "The latrine smelled really bad.",
            "dirty toilet",
            "Before lunch we looked for soap and water, but there was only a bucket, which made us uneasy about hygiene.",
            "Please keep the bathroom cleaner.",
        ],
        "fr": [
            "Les toilettes étaient franchement crasseuses.",
            "Il n'y avait aucun endroit pour se laver les mains.",
            "Les latrines sentaient très mauvais.",
            "toilettes sales",
            "Avant le repas on a cherché du savon et de l'eau, mais il n'y avait qu'un seau, peu rassurant pour l'hygiène.",
            "Merci de garder les toilettes plus propres.",
        ],
        "de": [
            "Die Toilette war richtig verdreckt.",
            "Es gab keine Möglichkeit, die Hände zu waschen.",
            "Die Latrine hat furchtbar gerochen.",
            "schmutzige toilette",
            "Vor dem Essen haben wir Seife und Wasser gesucht, es gab nur einen Eimer, wenig hygienisch.",
            "Bitte die Toilette sauberer halten.",
        ],
        "es": [
            "Los baños estaban asquerosos.",
            "No había dónde lavarse las manos.",
            "La letrina olía muy mal.",
            "baño sucio",
            "Antes de comer buscamos jabón y agua, pero solo había un cubo, poco higiénico.",
            "Por favor, mantengan el baño más limpio.",
        ],
    },
    "N8": {
        "en": [
            "It was very hot and we had nothing to drink.",
            "We walked for two hours without a single break.",
            "No shade anywhere in the fields.",
            "too hot, no water",
            "Some of us felt dizzy in the midday sun, a stop under a tree with water would have helped.",
            "We needed more breaks to rest.",
        ],
        "fr": [
            "Il faisait très chaud et on n'avait rien à boire.",
            "On a marché deux heures sans une seule pause.",
            "Aucune ombre dans les champs.",
            "trop chaud, pas d'eau",
            "Certains ont eu des vertiges en plein soleil, une halte à l'ombre avec de l'eau aurait aidé.",
            "Il nous fallait plus de pauses pour nous reposer.",
        ],
        "de": [
            "Es war sehr heiß und wir hatten nichts zu trinken.",
            "Wir sind zwei Stunden ohne eine einzige Pause gelaufen.",
            "Nirgends Schatten auf den Feldern.",
            "zu heiß, kein wasser",
            "Einigen von uns wurde in der Mittagssonne schwindlig, eine Rast im Schatten mit Wasser hätte geholfen.",
            "Wir hätten mehr Pausen zum Ausruhen gebraucht.",
        ],
        "es": [
            "Hacía mucho calor y no teníamos nada para beber.",
            "Caminamos dos horas sin un solo descanso.",
            "Ninguna sombra en los campos.",
            "mucho calor, sin agua",
            "Algunos se marearon bajo el sol del mediodía, una parada a la sombra con agua habría ayudado.",
            "Necesitábamos más pausas para descansar.",
        ],
    },
    "N9": {
        "en": [
            "We stood around waiting for ages at the start.",
            "The visit began much later than the time we were given.",
            "Our host arrived very late.",
            "started late",
            "We were ready at eight as agreed, but we sat in the car for almost an hour before anyone came.",
            "Better timekeeping please.",
        ],
        "fr": [
            "On a attendu une éternité au début.",
            "La visite a commencé bien plus tard que l'heure annoncée.",
            "Notre hôte est arrivée très en retard.",
            "commencé en retard",
            "On était prêts à huit heures comme convenu, mais on est restés presque une heure dans la voiture avant que quelqu'un arrive.",
            "Le programme a pris beaucoup de retard.",
        ],
        "de": [
            "Am Anfang haben wir ewig gewartet.",
            "Der Besuch begann viel später als die genannte Uhrzeit.",
            "Unsere Gastgeberin kam sehr spät.",
            "verspäteter beginn",
            "Wir waren wie vereinbart um acht bereit und saßen fast eine Stunde im Auto, bevor jemand kam.",
            "Bitte pünktlicher sein.",
        ],
        "es": [
            "Esperamos una eternidad al principio.",
            "La visita empezó mucho más tarde de la hora indicada.",
            "Nuestra anfitriona llegó muy tarde.",
            "empezó tarde",
            "Estábamos listos a las ocho como habíamos quedado, pero pasamos casi una hora en el coche hasta que llegó alguien.",
            "Por favor, sean más puntuales.",
        ],
    },
    "N10": {
        "en": [
            "We wanted coffee to take home but they had none to sell.",
            "There was no way to buy anything at the farm.",
            "They only took cash, so we left without coffee.",
            "couldn't buy coffee",
            "I asked about souvenirs or a bag of beans, but there was nothing available, a pity for visitors who want to support them.",
            "Sad we couldn't take any coffee home.",
        ],
        "fr": [
            "On voulait du café à rapporter mais il n'y en avait pas à vendre.",
            "Impossible d'acheter quoi que ce soit à la ferme.",
            "Ils ne prenaient que du liquide, donc on est partis sans café.",
            "pas pu acheter de café",
            "J'ai demandé des souvenirs ou un sachet de grains, mais rien n'était disponible, dommage pour les visiteurs qui veulent les soutenir.",
            "Dommage de ne pas avoir pu rapporter de café.",
        ],
        "de": [
            "Wir wollten Kaffee mitnehmen, aber es gab keinen zu kaufen.",
            "Auf der Farm konnte man nichts kaufen.",
            "Sie nahmen nur Bargeld, also sind wir ohne Kaffee gegangen.",
            "konnte keinen kaffee kaufen",
            "Ich habe nach Souvenirs oder einer Tüte Bohnen gefragt, es war nichts erhältlich, schade für Besucher, die sie unterstützen wollen.",
            "Schade, dass wir keinen Kaffee mitnehmen konnten.",
        ],
        "es": [
            "Queríamos llevarnos café pero no había para vender.",
            "En la finca no se podía comprar nada.",
            "Solo aceptaban efectivo, así que nos fuimos sin café.",
            "no pudimos comprar café",
            "Pregunté por recuerdos o una bolsa de granos, pero no había nada disponible, una pena para los visitantes que quieren apoyarlos.",
            "Qué pena no poder llevarnos café.",
        ],
    },
}
